### ISSUE TITLE
Upgrade Hugo

### ISSUE THREAD

**Issue by davkal** [grafana/grafana.org#156]
this instance is currently on 0.30, would be great to upgrade to a recent version so the widely available documentation is applicable.

@torkelo any idea why we stuck with 0.30? I remember you mentioned some linking

Note: a recent version produces an error about a missing layout, this needs to be fixed

**Comment by torkelo** [comment]
There was some bugs / breaking changes when I upgraded once and did not have time to troubleshoot & resolve them. 

@adeverteuil you upgrade the new docs site to latest hugo right? do you remember the upgrade issues?
