### ISSUE TITLE
[Bug] Title page shows v3.0.1 as the latest, but should show v3.0.2

### ISSUE THREAD

**Issue by zstyblik** [grafana/grafana.org#24]
Hello,

title page of http://grafana.org says ``Download(Latest v3.0.1)'', but v3.0.2 is the latest. I hope this is the correct place to report this.

Thanks.

**Comment by zstyblik** [comment]
I see https://github.com/grafana/grafana.org/commit/4f2fd59f03777d97e6204f3993317f53a316f07c has updated download section, but I guess https://github.com/grafana/grafana.org/blob/master/source/index.html.slim#L21 was missed.

**Comment by bulletfactory** [comment]
Thanks - This has been fixed.
