### ISSUE TITLE
Documentation of user roles

### ISSUE THREAD

**Issue by zstyblik** [grafana/grafana.org#26]
Hello,

please, could you document user roles in Grafana? As of now, one can find this information through multiple changelogs/release announcements. http://docs.grafana.org/reference/admin/ might be a good place for such information.

Expected:
- list of roles
- privileges of each and every role

Thanks.

**Comment by dannyk81** [comment]
:100: 
Indeed this is something that is quite scattered and difficult to follow.

**Comment by ricsil** [comment]
Just in case someone stumbles upon this from Google:

> All Dashboards and Data Sources are linked to an Organization (not to a User). Users are linked to Organizations via a role. That role can be:
> 
> Viewer: Can only view dashboards, not save / create them.
> Editor: Can view, update and create dashboards.
> Admin: Everything an Editor can plus edit and add data sources and organization users.

Source: http://docs.grafana.org/guides/whats-new-in-v2/

**Comment by daniellee** [comment]
This has now been documented here:

http://docs.grafana.org/administration/permissions/#organization-roles
