### ISSUE TITLE
RSS feed for the blog is gone

### ISSUE THREAD

**Issue by kaistian** [grafana/grafana.org#31]
The URL http://grafana.org/feed.xml doesn't work anymore, is it possible to get the feed back?

**Comment by simison** [comment]
Just broken link left at the sidebar:

```html
<a href="" type="application/rss+xml" target="_blank">
  RSS <i class="fa fa-rss"></i>
</a>
```

**Comment by bulletfactory** [comment]
Having @nchristus fix

**Comment by davkal** [comment]
The URL is https://grafana.com/blog/blog/index.xml now.
