### ISSUE TITLE
Docs: New Nav Structure

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana.org#34]
#### Installation
- Installation
- Installing on Debian/Ubuntu
- Installing on MacOS X
- Installing on Windows
- Installing on Docker
- Building from source
- Configuration
- LDAP Integration
- Provisioning
- Performance Tips
- Troubleshooting
- Migrating from v1.x to v2.x
#### User Guides
- Basic Concepts
- Getting Started
- What's New in Grafana v3.1
- What's New in Grafana v3.0
- What's New in Grafana v2.6
- What's New in Grafana v2.5
- What's New in Grafana v2.1
- What's New in Grafana v2.0
- Screencasts
#### Reference
- Graph Panel
- Singlestat Panel
- Table Panel
- Dashboard List Panel
- Sharing
- Annotations
- Time Range
- Search
- Templating
- Scripting
- Playlist
- Import & Export
- Administration
- Keyboard Shortcuts
#### Data Sources
- Overview
- Graphite
- Elsasticsearch
- Cloudwatch
- InfluxDB
- OpenTSDB
- KairosDB
- Prometheus
#### API
- Overview
- Authentication API
- Dashboard API
- Data Source API
- Organisation API
- User API
- Admin API
- Snapshot API
- Preferences API
- Other API
#### Plugins
- Overview
- Installation
- Development
- Apps
- Datasources
- Panels
#### Tutorials
- Tutorials
- How to integrate Hubot & Grafana
#### Installation
- Installation
- Installing on Debian/Ubuntu
- Installing on MacOS X
- Installing on Windows
- Installing on Docker
- Building from source
- Provisioning
- Troubleshooting
- Migrating from older versions(consolidate `v1.x to v2.x` and add section for 2.x to 3.x)
#### General
- Basic Concepts
- Getting Started
- Configuration
- Administration
#### Dashboards
- Graph Panel
- Singlestat Panel
- Table Panel
- Dashboard List Panel
- Sharing
- Annotations
- Templating
- Time Range
- Search
- Scripting
- Playlist
- Importing & Exporting
- Keyboard Shortcuts
#### Data Sources
- Overview
- Graphite
  - Performance Tips (moved from Installation, combine with this article)
- Elasticsearch
- Cloudwatch
- InfluxDB
- OpenTSDB
- KairosDB
- Prometheus
#### Alerting
- Lots
- of
- new
- content
#### Plugins
- Overview
- Installation
- Development
- Apps
- Datasources
- Panels
#### Users & Orgs
- Overview
- LDAP Integration
#### Extending Grafana
- Extending using Grafana.net
- How to integrate Hubot & Grafana
#### API
- Overview
- Authentication API
- Dashboard API
- Data Source API
- Organisation API
- User API
- Admin API
- Snapshot API
- Preferences API
- Other API

**Comment by torkelo** [comment]
nice

**Comment by torkelo** [comment]
A little bit more nested / deep structure, but gives us more room at top level and more structure. 

- Installation
  - Installing on Debian/Ubuntu 
  - Installing on MacOS X
  - Installing on Windows
  - Installing on Docker
  - Building from source
  - Provisioning (Puppet, Chef, etc)
  - Troubleshooting
  - Migrating from older versions

- Administration 
  - Server Configuration
  - Authentication (OAuth / Proxy Auth)
  - Authentication LDAP
  - User & Orgs
  - Backups

- Feature Guides
 - Getting Started
    - Basic Concepts
    - Your first dashboard
 - Dashboard Panels
    - Graph Panel
    - Singlestat Panel
    - Table Panel
    - Dashboard List Panel
 - Dashboard Features
    - Sharing
    - Annotations
    - Templating
    - Time Range
    - Search
    - Scripting
    - Playlist
    - Importing & Exporting
    - Keyboard Shortcuts
 - Data Sources
    - Graphite
    - Elasticsearch
    - Cloudwatch
    - Performance Tips (moved from Installation, combine with this article)
 - Alerting
      - Lots
      - of
 - Plugins
    - Overview
    - Installation
    - Development
    - Apps
    - Datasources
    - Panels
- Extending Grafana
  - Extending using Grafana.net
  - How to integrate Hubot & Grafana
- HTTP API
  - Overview
  - Authentication API
  - Dashboard API
  - Data Source API

**Comment by torkelo** [comment]
Demo http://staging-docs.grafana.org/

Maybe it's a bit too nested?

**Comment by davkal** [comment]
Outdated.
