### ISSUE TITLE
Images broken on blog

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana.org#36]
Example: http://grafana.org/blog/2016/04/08/timing-is-everything.-writing-the-clock-panel-plugin-for-grafana-3.0/

It's pointing to `src="blog/clock_panel_unstyled.png"`,
should be `src="assets/img/blog/clock_panel_unstyled.png"`

![screenshot 2016-11-02 14 05 41](https://cloud.githubusercontent.com/assets/2886187/19941200/94411504-a105-11e6-8fa7-bce5a45c9918.png)

**Comment by alexanderzobnin** [comment]
The same thing for docs. I get 403 (Forbidden) error for images request.
