### ISSUE TITLE
Windows download link on site incorrect

### ISSUE THREAD

**Issue by sirpengi** [grafana/grafana.org#37]
Trying to download latest stable from http://docs.grafana.org/installation/windows/ and the link fails.  The current link (https://grafanarel.s3.amazonaws.com/winbuilds/dist/grafana-3.1.1.windows-x64.zip) is wrong. It appears it should instead be: https://grafanarel.s3.amazonaws.com/builds/grafana-3.1.1.windows-x64.zip

**Comment by torkelo** [comment]
thanks! will fix
