### ISSUE TITLE
Incorrect documentation for Docker?

### ISSUE THREAD

**Issue by AlekSi** [grafana/grafana.org#40]
[Site](http://docs.grafana.org/installation/docker/) says that two volumes are exposed: `/var/lib/grafana` and `/etc/grafana/`.
[Dockerfile](https://github.com/grafana/grafana/blob/v4.0.2/docker/production/Dockerfile) exposes `/opt/grafana/data` and `/opt/grafana/conf`.
Which one is right?

**Comment by bhaku** [comment]
@AlekSi I think this [Dockerfile](https://github.com/grafana/grafana/blob/v4.0.2/docker/production/Dockerfile) is old, look at git log. For now they use [this repositry](https://github.com/grafana/grafana-docker) to generate images. 
This  [Dockerfile](https://github.com/grafana/grafana-docker/blob/master/Dockerfile#L17) define three mount points: 
`VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"] `

You can also check it by run Grafana container and check volumes with cmd:

`docker inspect -f '{{ .Config.Volumes }}' grafana`
