### ISSUE TITLE
HTTPS support for grafana.org

### ISSUE THREAD

**Issue by jsha** [grafana/grafana.org#42]
Hi,

I work on EFF's [Encrypt the Web](https://www.eff.org/encrypt-the-web) campaign, and also on the Let's Encrypt free and automated certificate authority. I'm also a happy user of Grafana.

I notice that grafana.org doesn't currently have HTTPS. What are the obstacles to making that happen? Is there anything I can help with?

Thanks,
Jacob

**Comment by pgporada** [comment]
Grafana.org now has HTTPS, but the following still do not

- http://stats.grafana.org 
- http://play.grafana.org
- http://staging.grafana.org
- http://docs.grafana.org

**Comment by davkal** [comment]
Those are all being redirected to https now.
