### ISSUE TITLE
Docs Navigation and sidebar overlap footer

### ISSUE THREAD

**Issue by bulletfactory** [grafana/grafana.org#43]
Open 2 random nav sections on docs and you'll see that it will overlap the footer. This may be because the sidebars are absolutely positioned. A fix may be to implement a the grid system for sidebars and main content area.

screenshot showing the issue:
<img width="1265" alt="screen shot 2017-02-22 at 1 50 08 pm" src="https://cloud.githubusercontent.com/assets/1950595/23227118/fbac1524-f905-11e6-9fcf-c1e5b0f2a70d.png">

**Comment by davkal** [comment]
Fixed.
