### ISSUE TITLE
Unavailable releases mentioned on 'Performance' docs page

### ISSUE THREAD

**Issue by grahamlyons** [grafana/grafana.org#5]
The docs section `source/docs/performance/index.md` mentions performance issues in versions lower than `0.9.12` and suggests running `0.9.13`. The 'Download' page only offers `0.9.11`, and indeed the main repo seems to suggest that `0.9.11` is the latest version.

Is a new release imminent or are these numbers a mistake?

**Comment by torkelo** [comment]
There should be a link to 0.9.13 release page in the performance doc page. I think 0.9.13 is RC1 (release candidate) . I really recommend it above 0.9.12
