### ISSUE TITLE
"Dashboard Version History" in 4.1+ docs but added in 4.4

### ISSUE THREAD

**Issue by CNG** [grafana/grafana.org#73]
That the page http://docs.grafana.org/v4.1/reference/dashboard_history/ exists seems to imply the feature exists in Grafana 4.1, but it seems it was added ([https://github.com/grafana/grafana/pull/8472](https://github.com/grafana/grafana/pull/8472)) in [4.4.0 (2017-07-04)](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#440-2017-07-04) and I cannot find the feature in my local install of Grafana 4.1.2. After a bit of searching around, I could not easily see where this was configured, so I'm submitting this as an issue instead of a pull request. :)

**Comment by Wiphawrrn63** [comment]
Line

**Comment by davkal** [comment]
Outdated.

**Comment by CNG** [comment]
Hey @davkal, by "outdated" I assume you mean you guys will make no effort to correct documentation for any already released version (as in, you will NEVER accept a pull request or do anything other than close an issue related to documentation). Is that correct, or am I misunderstanding? I'm thinking you might as well delete all documentation except that of the latest version if it cannot be depended upon.
